# Generated by Django 4.0.3 on 2022-04-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndata',
            name='poll_camp',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usermanag.poll'),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='poll_form_camp',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usermanag.poolform'),
        ),
    ]
