# Generated by Django 4.0.3 on 2022-04-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanag', '0002_alter_campaigndata_poll_camp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaing',
            name='id_campaign',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id_poll',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poolform',
            name='id_form',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
