# Generated by Django 4.0.3 on 2022-04-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanag', '0005_alter_campaigndata_poll_camp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndata',
            name='camp_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanag.campaing'),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='house_camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanag.house'),
        ),
    ]
