# Generated by Django 4.0.3 on 2022-05-03 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanag', '0006_alter_campaigndata_camp_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndata',
            name='user_camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
