# Generated by Django 4.0.3 on 2022-05-03 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanag', '0007_alter_campaigndata_user_camp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndata',
            name='camp_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanag.campaing', verbose_name='Кампания'),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='house_camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanag.house', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='poll_camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanag.poll', verbose_name='Обход'),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='poll_form_camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanag.poolform', verbose_name='Форма обхода'),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='user_camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
